#!/usr/bin/env bash
# Installs or updates bashblog
# Available at: https://github.com/cfenollosa/bashblog
#
# Execution flow:
#   1. Resolve fixed paths from the script location (independent of the current directory)
#   2. Parse command-line options (-h for help)
#   3. If bb.sh already exists: back it up and record the previous version
#   4. Download bb.sh from the official repository to a temporary file
#   5. Validate the downloaded content before replacing the existing script
#   6. Install the new bb.sh at the blog root (with execute permission)
#   7. Report install vs update, comparing versions
#   8. Suggest rebuild if published posts already exist
#   9. Check whether $EDITOR is set (required to create/edit posts)

# Exit on first failure (-e), unset variables (-u), and pipeline errors (-o pipefail)
set -euo pipefail

# URL of the main script on the official repository master branch
URL="https://raw.githubusercontent.com/cfenollosa/bashblog/master/bb.sh"

# Directory containing this script (sh/), regardless of where it was invoked from
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Blog root is the parent directory of sh/
BLOG_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
# Final path where bb.sh should be installed
TARGET="$BLOG_ROOT/bb.sh"

# Show usage when the user passes -h
usage() {
    cat <<EOF
Usage: $(basename "$0") [-h]

Downloads bb.sh from the official repository and installs it at:
  $TARGET

Options:
  -h  Show this help

The .config file at the blog root is not modified.
EOF
}

# Extracts bashblog version from a bb.sh file (e.g. "2.10"), or "" if not found
get_version() {
    local file="$1" # Path to the bb.sh file
    if [[ ! -f "$file" ]]; then # File does not exist
        echo "" # Return an empty string
        return
    fi
    local version="" # Holds the bashblog version string
    # grep -m1: first line with global_software_version= (e.g. global_software_version="2.10")
    # sed: extract only the quoted value (2.10). The if assigns the pipeline to version and
    # requires [[ -n "$version" ]]; with set -e (line 17), a failed grep (no match) does not abort.
    if version="$(grep -m1 'global_software_version=' "$file" \
        | sed -n 's/.*global_software_version="\([^"]*\)".*/\1/p')" && [[ -n "$version" ]]; then
        echo "$version" # Return the bashblog version
        return 0
    fi
    echo "" # Return empty if version was not found
}

# True if published posts exist at the blog root (maxdepth 1 only; drafts in subdirs do not count)
has_posts() {
    local html_files
    # Skip HTML generated by bashblog, not author posts:
    #   index.html   — home page
    #   all_*.html   — e.g. all_posts.html, all_tags.html
    #   tag_*.html   — tag listing pages
    # -print -quit: stop at first match. 2>/dev/null || true: avoid aborting with set -e.
    html_files="$(find "$BLOG_ROOT" -maxdepth 1 -name '*.html' \
        ! -name 'index.html' ! -name 'all_*.html' ! -name 'tag_*.html' \
        -print -quit 2>/dev/null || true)"
    [[ -n "$html_files" ]]
}

# Downloads bb.sh to the given path, using curl or wget (whichever is available)
download() {
    local dest="$1" # Destination path for the downloaded file
    if command -v curl >/dev/null 2>&1; then # curl is available
        curl -fsSL -o "$dest" "$URL" # Download with curl
    elif command -v wget >/dev/null 2>&1; then # wget is available
        wget -q -O "$dest" "$URL" # Download with wget
    else
        echo "Error: curl or wget is required to download bashblog." >&2
        exit 1 # Neither curl nor wget is available
    fi
}

# Checks that the downloaded file looks like a valid bb.sh before installing
validate_bb_sh() {
    local file="$1"
    # Empty file usually means a failed download
    if [[ ! -s "$file" ]]; then
        echo "Error: downloaded file is empty." >&2
        return 1
    fi
    # Every bash script starts with a shebang; rejects HTML error pages, for example
    if ! head -n1 "$file" | grep -q '^#!/usr/bin/env bash'; then
        echo "Error: downloaded file does not look like a valid bash script." >&2
        return 1
    fi
    # Signature marker of bashblog; distinguishes it from generic bash scripts
    if ! grep -q 'global_software_name=' "$file"; then
        echo "Error: downloaded file does not look like bashblog." >&2
        return 1
    fi
}

# Warns if $EDITOR is unset; bashblog needs it to open the post editor
check_editor() {
    if [[ -n "${EDITOR:-}" ]]; then
        return 0
    fi

    echo ""
    echo "Warning: \$EDITOR is not set."
    echo "Bashblog uses \$EDITOR to open the editor when creating or editing posts."
    echo ""
    echo "Set it for the current session (pick an editor):"
    echo "  export EDITOR=nano"
    echo "  export EDITOR=vim"
    echo "  export EDITOR=nvim"
    echo ""
    echo "To make it permanent, add your chosen line to ~/.bashrc or ~/.profile."
}

# --- Main execution ---

# Parse -h; unknown options print help and exit with an error
while getopts ':h' opt; do
    case "$opt" in
        h) usage; exit 0 ;; # Show help and exit
        *) usage >&2; exit 1 ;; # Show help and exit with error
    esac
done

# Track whether this is a fresh install or an update
old_version=""
is_update=false

# Existing bb.sh: treat as update, save version, and create a timestamped backup
if [[ -f "$TARGET" ]]; then
    is_update=true
    old_version="$(get_version "$TARGET")"
    backup="$TARGET.bak.$(date +%Y%m%d%H%M%S)"
    cp -a "$TARGET" "$backup" # Timestamped backup for rollback
    echo "Backup created: $backup"
fi

# Download to a temp file; replace bb.sh only after validation (atomic install)
tmp="$(mktemp)"
# Remove the temp file if the script exits before install completes
trap 'rm -f "$tmp"' EXIT

echo "Downloading bashblog from $URL ..."
download "$tmp"
validate_bb_sh "$tmp"

# Make executable, move to final destination, and clear the temp-file trap
chmod +x "$tmp"
mv "$tmp" "$TARGET"
trap - EXIT # Temp file already moved; drop the cleanup trap

# Read version from the newly installed bb.sh for comparison
new_version="$(get_version "$TARGET")"

# Completion message: install or update, with version comparison when possible
if [[ "$is_update" == true ]]; then
    if [[ -n "$old_version" && -n "$new_version" && "$old_version" == "$new_version" ]]; then
        echo "Bashblog updated (version $new_version, no version change)." # Same version after update
    elif [[ -n "$old_version" && -n "$new_version" ]]; then
        echo "Bashblog updated: $old_version → $new_version" # Version changed
    else
        echo "Bashblog updated at $TARGET" # Old or new version unknown
    fi
else
    if [[ -n "$new_version" ]]; then
        echo "Bashblog installed (version $new_version) at $TARGET" # Fresh install, version known
    else
        echo "Bashblog installed at $TARGET" # Fresh install, version unknown
    fi
fi

# After updating bb.sh, rebuild regenerates index, RSS, and tags (when posts exist)
if has_posts; then
    echo ""
    echo "Published posts found. Recommended: regenerate the site:"
    echo "  cd \"$BLOG_ROOT\" && ./bb.sh rebuild"
fi

# Without $EDITOR, commands like ./bb.sh post cannot open an editor (required to create/edit posts)
check_editor
